### ISSUE TITLE
add/exclude HTTP status code filter for fuzz

### ISSUE THREAD

**Issue by rudSarkar** [pwnwriter/kanha#1]
Hi,

I am creating this issue for adding/excluding `-is or --include-status` and `-es or --exclude-status` to filter HTTP status code because it's missing the feature in fuzz, Making lots of requests and there is no way to get the exact filtering for HTTP status code.

Looking forward to hearing from you.

Thanks

**Comment by pwnwriter** [comment]
Hello @rudSarkar ,

I have plans to include those features in the next release. I didn't add them just to make it less intimidating. Give me a day, will release it with those features, along with some additional subcommands :)

**Comment by rudSarkar** [comment]
@pwnwriter update version of kanha for cargo

**Comment by pwnwriter** [comment]
Hey @rudSarkar , Sorry for the late response. I'll **update(***release***)** `kanha` version after adding some more desired features.  You can test out exclude args if you wish :bear:
