### ISSUE TITLE
[bug] An unexpected error occurred in kanha

### ISSUE THREAD

**Issue by enomothem** [pwnwriter/kanha#25]
### Description

- windows 10
- rustc 1.73.0 (cc66ad468 2023-10-03)
- cargo 1.73.0 (9c4383fb5 2023-08-26)

` --exclude`  没猜错的话，应该是排除状态码的参数，但是出现了报错，我不认为这是正常的。

是否可以增加一个只显示指定的状态码的参数。例如：

`--status-code 200`

### Software Version

latest v0.1.2

### Steps to Reproduce

An unexpected error occurred in kanha

`.\kanha.exe status -f .\e.txt --exclude 404,403`

ps: 仅测试目的，并无针对性使用工具测试这些目标
![image](https://github.com/pwnwriter/kanha/assets/45089051/ee55b40e-78c2-4695-88b2-04a01e7cab83)

### Expected Behavior

no error

### Actual Behavior

error

**Comment by enomothem** [comment]
The reason should be this debug command, which I resolved after commenting.
```
// dbg!("{:?}", url.clone());
```

**Comment by pwnwriter** [comment]
Nice catch, i didn't commented while debugging , Ty :<3
